### ISSUE TITLE
travel_agency template won't import

### ISSUE THREAD

**Issue by macubergeek** [pentestgeek/phishing-frenzy-templates#10]
linked in and the Powershell template seemed to import but when I try to import the travel_agency.zip I get the rails error "Something went Wrong"

**Comment by zeknox** [comment]
You most likely do not have proper permissions set on the uploads dir, please see troubleshooting section on the official website for info on how to debug this generic rails error message.

Once you have a more specific error message from the log file please include that here so we can determine the underlying issue.
