### ISSUE TITLE
[Question] Intel Template

### ISSUE THREAD

**Issue by TheRapture** [pentestgeek/phishing-frenzy-templates#13]
Hey there!
I am trying to find the Intel password checker template, and I'm not seeing it.  I am new to the GitHubz, so maybe I'm just doing it wrong, but any help would be appreciated!

**Comment by zeknox** [comment]
It is built-in to the PF application itself.  I believe you need to run:

<pre>$ rake templates:load</pre>

If your running your app in production mode you will need to specify the env:

<pre>$ RAILS_ENV=production rake templates:load</pre>

**Comment by TheRapture** [comment]
Man, you are fast!
I will give it a try and let you know if I've got it fixed.
Isn't that issued during the installation?  I have it all installed but its just not in the templates.  No templates were there when I initially ran the program, I loaded the ones that are there now.

**Comment by TheRapture** [comment]
whoops, didn't mean to close it yet

**Comment by zeknox** [comment]
Yes, it is part of the normal install process.  If you ran it perhaps you ran it for the wrong environment (e.g rake ran in development mode but app is running in production mode).

You can find out what mode your rails app is running in by looking at the apache config file:

<pre>/etc/apache2/pf.conf</pre>

**Comment by TheRapture** [comment]
Everything works fine though, I ran a pretty successful campaign yesterday and everything. If I would have installed it incorrectly, would it still be possible to have done that?  I remember doing this part:

Change the permissions of the directory to grant us proper permissions to carry on with the install. Replace the "username" placeholder below with your actual username.

 $ sudo chown -R "username":www-data /var/www/phishing-frenzy/
Change permissions on the upload directory to allow the rake templates:load to import the default templates properly.

 $ sudo chmod -R 755 /var/www/phishing-frenzy/public/uploads/
 $ cd /var/www/phishing-frenzy/
 $ bundle install
If your web application fails to run because it states your missing a gem, you may need to run

$ bundle install --deployment
$ rake db:migrate
$ rake db:seed

**Comment by TheRapture** [comment]
Is it possible to just install the templates manually from anywhere?

**Comment by zeknox** [comment]
<pre>$ rake templates:load </pre>

As of now this is the only manual way to install the 2 built-in templates. The files are however all included within the phishing-frenzy directory so you could 1-by-1 put the template together.

**Comment by TheRapture** [comment]
I just get: 
root@rails:~# rake templates:load
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in`<main>'
(See full trace by running task with --trace)

**Comment by zeknox** [comment]
Thats because you are not in the proper /var/www/phishing-frenzy directory where the rake tasks are located.

**Comment by TheRapture** [comment]
brilliant! haha  I am such a doof, thanks so much, and your program is fricking amazing, I mean it!  I am new to the pentesting field, and so this is my first time doing phishing campaigns.  I have done a bunch of research into your program, including watching your talk on it at derbycon on irongeek.  Anyway, I just wanted to let you know I appreciate your hard work and lightning quick responses!
_Redacted client name_

![image](https://cloud.githubusercontent.com/assets/13596679/11594671/f1341500-9a70-11e5-95db-0a99d1773926.png)

**Comment by zeknox** [comment]
Appreciate the feedback, enjoy!

**Comment by TheRapture** [comment]
You are the best!  I will!
